__author__ = 'Hadeslee'
print('hello world'.capitalize())
print('hello world'.upper())
print('hello world'.__len__())
print(len('hello world'))
print('Hello world'.replace('world', 'programming'))
print("hadeslee's \"tutorial\"")
print("\\")
print("Hello \nworld")
print("Hello \tworld")
print("Hello \t\tworld")
print("\a")
print('Hello\nworld')